name: five-column-layout

services:
  demo:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html
    restart: always
    container_name: five-column-layout-demo